name = "MzCore"
uuid = "0ec0bfde-29d9-4330-bf45-ac65ec309208"
authors = ["Tim Holy <tim.holy@gmail.com> and contributors"]
version = "0.1.0"

[deps]
AxisArrays = "39de3d68-74b9-583c-8d2d-e117c070f3a9"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
